name: fruitzshop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.2+1
  cupertino_icons: ^1.0.2
  mobx: ^1.2.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.11.1
  mobx_codegen: ^1.1.2
  flutter_mobx: ^1.1.0+2  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BadScript
      fonts:
        - asset: assets/fonts/BadScript-Regular.ttf
       # - asset: fonts/Schyler-Italic.ttf
         # style: italic
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

    - family: Montserat
      fonts:
        - asset:  assets/fonts/Montserrat-Regular.ttf

    - family: OpenLight
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Light.ttf

    - family: Roboto
      fonts:
        - asset:  assets/fonts/RobotoMono-Regular.ttf

    - family: Lato
      fonts:
      - asset: assets/fonts/Lato-Thin.ttf

    - family: Cuprum
      fonts:
        - asset: assets/fonts/Cuprum-Regular.ttf
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          style: italic

    - family: SpectralSCItalic
      fonts:
        - asset: assets/fonts/SpectralSC-Italic.ttf
          style: italic

    - family: Nino
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
            
    - family: IBMTHIN
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.ttf

    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.ttf   

    - family: Spectral-Sc
      fonts:
      - asset: assets/fonts/SpectralSC-ExtraLight.ttf

    - family: Noto
      fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf

    - family: Nunito 
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
     
    - family: ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf

    - family: PTS
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf  

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
